export const bookImg="/images/rr.jpg"
export const bookCradimg="/images/card-bg.png"
export const back1="Back Row Seat"
export const back2="Free Lunch & Snacks"
export const back3="Event Certificate"
export const back4="1 Workshop"
