export const footerMinHead1="Vanue Location"
export const footerMinHead2="Exevent"
export const footerMinHead3="Contact With us"
export const footerbgimg="/images/footer-img/footer-shape-1.png"
export const footertext="All Right Reserved RRInfosoft "