export const EventSchdules="Event Schedule"
export const EventSchduleTitle="Without waiting for you to catch up"
export const EventNob1="1st Day"
export const EventNob2="2nd Day"
export const EventNob3="3rd Day"
export const EventNob4="4th Day"
export const EventBg="/images/events6.png"
export const EventBg2="/images/events7.png"
export const Enob="12"
export const Aug="August"
export const Aug2="09:00 - 11:00 AM"
export const circleimg="/images/eve-1.png"
export const monthon=" Monthon city hall, New York"
export const Regis="Registration for opening workshop"
export const weText="We’re inviting the top creatives in the tech industry from all over the world to come learn, grow, scrape their knees, try new things, to be vulnerable, epic adventures"
export const epic="epic adventures Meh synth Schlitz, tempor duis single-origin coffee ea next level ethnic fingerstache fanny pack nostrud. Photo booth anim 8-bit hella, PBR 3 wolf moon beard Helvetica. Salvia esse flexitarian Truffaut synth art party deep v chillwave."

